### ISSUE TITLE
baker and endorser need password

### ISSUE THREAD

**Issue by ffallah** [etomknudsen/tezos-baking#1]
How to enter the password using systemd services ?

**Comment by ericlavoie** [comment]
no solution for this correct?

**Comment by utdrmac** [comment]
In theory, you would run `tezos-signer` which would accept your password to unlock key and then run in the background. `baker` and `endorser` would connect to the signer when needing to sign a block. This should allow for baker/endorser to restart without needing password input. I haven't tested this though; only read docs.

**Comment by keefertaylor** [comment]
I think the following will work using `expect`.

Assuming your baker's identity is `my_baker` and your password is `baker_password`, you could put the following a file called `run baker.sh`:

```
#!/usr/bin/expect -f
set timeout -1
spawn /home/ubuntu/tezos/tezos-baker-002-PsYLVpVv  run with local node "/home/ubuntu/.tezos-node" my_baker
expect "Enter password for encrypted key \"my_baker\":" {send -- "baker_password\r"}

expect eof
```

Then to run:
```
# Install expect
$ sudo apt-get install expect

# Run the baker
$ ./run_baker.sh
```

This script could be improved by reading out of environment variables so things aren't hardcoded. I haven't looked into that but I'm sure it's possible. 

Theoretically, you could use a signer to do this, but I think that a local signer will still have the password hardcoded on the machine somewhere (or require you to be around to input it) so I'm not really sure there's a security advantage. Someone more knowledgeable should feel free to correct me if I'm wrong.

**Comment by utdrmac** [comment]
I've been curious about using Vault (or other Cloud-provided "secrets storage") to store the password and be retrieved natively using tezos-signer. However, I keep running into the issue of storing the Vault identifier/path in a config file on disk. If an attacker gains access to the disk, they can read the config file and make manual API requests to retrieve the password.

**Comment by keefertaylor** [comment]
Just OOC, do you mind sharing the commands that you're using to get a signer running? I haven't looked into it too much but it wasn't obvious from a glance at the documentation.

**Comment by utdrmac** [comment]
This is what I followed: https://github.com/maxtez-raspbaker/tezos-rpi3/wiki/%5Bs-2%5D-Learn-how-to-use-the-tezos-signer-program-with-a-tcp-port-or-a-unix-socket

```
-- Import encrypted key to signer and start signer using unix socket
./tezos-signer import secret key <keyName> encrypted:edesk....
./tezos-signer launch local signer -s /path/to/socket

-- Import public key to client
./tezos-client import secret key <keyName> unix:/path/to/socket?pkh=tz1....

-- Start baker/endorser
./tezos-baker-002-PsYLVpVv -R unix:/path/to/socket?pkh=tz1... run with local node /path/to/node/ <keyName>
./tezos-endorser-002-PsYLVpVv -R unix:/path/to/socket?pkh=tz1... run <keyName>
```

**Comment by etomknudsen** [comment]
Signer here: https://github.com/etomknudsen/tezos-baking/blob/master/tezos-signer.service

**Comment by etomknudsen** [comment]
Recommend you run it over an SSH tunnel: https://github.com/etomknudsen/tezos-baking/blob/master/tezos-signer-tunnel.service
