### ISSUE TITLE
tezos-node run --rpc-addr 127.0.0.1:8732 Fails

### ISSUE THREAD

**Issue by Ulysseus** [etomknudsen/tezos-baking#3]
If I try and run the node with rpc enabled  I get this, not sure if this is expected behavior.

ExecStart=/home/don/tezos/tezos-node run --rpc addr 127.0.0.1:8732 (code=exited, status=1/FAILURE)

But thanks for the files.

**Comment by ondrapaulicek** [comment]
Hi,

Your parameter is wrong (rpc addr should rpc-addr)

Andrew

**Comment by etomknudsen** [comment]
Thanks Andrew.
