### ISSUE TITLE
Line 35 causing traceback error in Node CPR script

### ISSUE THREAD

**Issue by nickman602** [etomknudsen/tezos-baking#4]
Hello,

This part of line #35 in particular throws an error on my local and cloud nodes when I run the node cpr script:
`curl -s $RPC_HOST:$RPC_PORT/network/stat | python3 -c "import sys, json; array = json.load(sys.stdin); print(int(array['total_recv'])+int(array['total_sent']))"`

The same piece of code I enter at command line:
`curl -s 127.0.0.1:8732/network/stat | python3 -c "import sys, json; array = json.load(sys.stdin); print(int(array['total_recv'])+int(array['total_sent']))"`

Both running the script and the code at command line give the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This line at the command line works fine:
`curl -s 127.0.0.1:8732/network/stat`

and returns:
`{"total_sent":"1287292","total_recv":"1562390","current_inflow":66,"current_outflow":63}`

I found that changing this part of line 35 to the below fixes the issue and properly reports back the values, specifically **json.loads(sys.stdin.read())**:
`curl -s $RPC_HOST:$RPC_PORT/network/stat | python3 -c "import sys, json; array = json.loads(sys.stdin.read()); print(int(array['total_recv'])+int(array['total_sent']))"`

The script runs fine with the error but I suspect that those using it are not actually getting the correct p2p data and don't know it!

**Comment by etomknudsen** [comment]
Have not been able to recreate issue.
