### ISSUE TITLE
Potential bugs in script functions

### ISSUE THREAD

**Issue by amani1104** [etomknudsen/tezos-baking#8]
I believe there are bugs both in the `getTimeSinceLastBlock` and the `getTotalTxp2p` functions. The script is configured to restart the node after 180s when no block arrived during this time. However, it fails to do so, as indicated, for instance, by the following line:

`2019-03-23T06:55:56Z Waiting. Last block was 515 secs ago`

I observed that the moment when I manually restart the node, strangely the script also fires. The log then shows an error in line 33, which is the `getTimeSinceLastBlock` function:

`Looking for p2p avtivity - will wait for max 90 secs`
`Waiting. Last block was 510 secs ago)`
`Waiting. Last block was 515 secs ago)`
`Traceback (most recent call last):`
`File "<string>", line 1, in <module>`
`File "/usr/lib/python3.6/json/__init__.py", line 299, in load`
`parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)`
`File "/usr/lib/python3.6/json/__init__.py", line 354, in loads`
`return _default_decoder.decode(s)`
`File "/usr/lib/python3.6/json/decoder.py", line 339, in decode`
`obj, end = self.raw_decode(s, idx=_w(s, 0).end())`
`File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode`
`raise JSONDecodeError("Expecting value", s, err.value) from None`
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
`date: invalid date '+%s'`
`/usr/local/bin/tezos-node-cpr.sh: 33: /usr/local/bin/tezos-node-cpr.sh: arithmetic expression: expecting primary: "1553324161-"`
`Network OK. No p2p activity and/or too long ( secs since last block. Restarting node!`

As reported by @nickman602 there has also been an error in the `getTotalTxp2p` function, which I had solved by following his suggestions. However, since the most recent node update (commit hash: 366f64f3..) also this functions does not seem to work any longer, as the node seems to receive and send some data also when it is not connected to any other peer. This is indicated by the following:

`2019-03-23T06:55:35Z Waiting. Last block was 494 secs ago)`
`2019-03-23T06:55:40Z Found p2p activity`
`2019-03-23T06:55:40Z Looking for p2p avtivity - will wait for max 90 secs`
`2019-03-23T06:55:40Z Waiting. Last block was 499 secs ago)`
`2019-03-23T06:55:45Z Found p2p activity`
`2019-03-23T06:55:45Z Looking for p2p avtivity - will wait for max 90 secs`
`2019-03-23T06:55:45Z Waiting. Last block was 504 secs ago)`
`2019-03-23T06:55:51Z Found p2p activity`

Both issues result in the script not automatically restarting the node any longer.

**Comment by etomknudsen** [comment]
Have not been able to verify issue.
